#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Dec 21 12:26:32 CET 2021
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 99651388c7cd4639b615f9df571421de --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot driver_pwm_rgb_single_tb_behav xil_defaultlib.driver_pwm_rgb_single_tb -log elaborate.log"
xelab -wto 99651388c7cd4639b615f9df571421de --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot driver_pwm_rgb_single_tb_behav xil_defaultlib.driver_pwm_rgb_single_tb -log elaborate.log

